<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="GC02TD4EPG8WNE" failures="1" tests="1" name="Default test" time="3.264" errors="0" timestamp="20 Sep 2019 06:39:42 GMT">
  <testcase classname="com.dc.datacreator.tests.DataTest" name="createTechtest" time="3.237">
    <failure type="org.json.JSONException" message="A JSONObject text must begin with &amp;apos;{&amp;apos; at 0 [character 1 line 1]">
      <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]at org.json.JSONTokener.syntaxError(JSONTokener.java:505)at org.json.JSONObject.<init>(JSONObject.java:215)at org.json.JSONObject.<init>(JSONObject.java:399)at com.dc.datacreator.lib.RestLib.getObjectRecordID(RestLib.java:122)at com.dc.datacreator.tests.DataTest.createTechtest(DataTest.java:194)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- createTechtest -->
  <testcase classname="com.dc.datacreator.tests.DataTest" name="producttest" time="0.0">
    <ignored/>
  </testcase> <!-- producttest -->
  <testcase classname="com.dc.datacreator.tests.DataTest" name="casetest" time="0.0">
    <ignored/>
  </testcase> <!-- casetest -->
  <testcase classname="com.dc.datacreator.tests.DataTest" name="locationtest" time="0.0">
    <ignored/>
  </testcase> <!-- locationtest -->
  <testcase classname="com.dc.datacreator.tests.DataTest" name="accountTest" time="0.0">
    <ignored/>
  </testcase> <!-- accountTest -->
  <testcase classname="com.dc.datacreator.tests.DataTest" name="contacttest" time="0.0">
    <ignored/>
  </testcase> <!-- contacttest -->
  <testcase classname="com.dc.datacreator.tests.DataTest" name="createTeamtest" time="0.0">
    <ignored/>
  </testcase> <!-- createTeamtest -->
</testsuite> <!-- Default test -->
