<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GC02TD4EPG8WNE" failures="0" tests="1" name="com.dc.datacreator.tests.DCRulesTest" time="1.791" errors="1" timestamp="25 Sep 2019 10:34:44 GMT" skipped="0">
  <testcase classname="com.dc.datacreator.tests.DCRulesTest" name="eventHovertest" time="1.791">
    <error message="A JSONObject text must begin with &#039;{&#039; at 0 [character 1 line 1]" type="org.json.JSONException">
      <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]at org.json.JSONTokener.syntaxError(JSONTokener.java:505)at org.json.JSONObject.<init>(JSONObject.java:215)at org.json.JSONObject.<init>(JSONObject.java:399)at com.dc.datacreator.lib.RestLib.getOauthAccessToken(RestLib.java:75)at com.dc.datacreator.lib.RestLib.getObjectRecordID(RestLib.java:87)at com.dc.datacreator.tests.DCRulesTest.eventHovertest(DCRulesTest.java:29)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- eventHovertest -->
</testsuite> <!-- com.dc.datacreator.tests.DCRulesTest -->
